### ISSUE TITLE
When building i686 package on x86_64 host mock should have yum preload some shared libraries

### ISSUE THREAD

**Issue by xning** [rpm-software-management/mock#15] opened 2016-11-10 11:13 UTC
When we building i686 package on an x86_64 host, mock will start a yum process that comes from a 64bit program. Because _dynamic loader_'s feature, it's possible that yum doesn't load some shared libraries.

But after calling _chroot_, _yum_ perhaps need load these share libraries. But because it's a 64 process, while the new root file system contains a 32bit env, hence the _dynamic loader_ cannot find out these libraries. This failure could cause dead lock and other troubles.

For example, if the host enable _nscd_ daemon, then the _libnss\_files.so_ will causes _yum_ failed when it calling _chown_ or _lchown_.

**Comment by xning** [comment] 2016-11-10 11:14
I think we need check each possible directives of rpm spec file, and make sure these libraries be loaded.

**Comment by xsuchy** [comment] 2016-11-11 08:47
Can you provide real-life reproducer?

I *think* your example does not work, because most scriptlets are called via shell so any binary in scriptlet is actually called as 32 bit binary.

**Comment by xning** [comment] 2016-11-14 08:49
@xsuchy suppose I will install a package fake.i686 on CentOS 6 x86_64 host by _mock_ command and the following situations are true

1. _fake_ package requires _fake-lib_ package, which will create _fakeuser_ and _fakegroup_ in its preinstall script let

2. there is following lines in the fake.spec file hence _yum_ will call call _chown_ function when installing _fake_ package

     %files
     %defattr(644,fakeuser,fakegroup,755)

3. Start _nscd_

Then, following steps will produce such error messages

    warning: group fakegroup does not exist - using root\n

1. Initlize a build env

         mock --init

2. Install the _fake_ package

         mock --install fake

While _fake-lib_ successfully created _fakeuser_ and _fakegroup_, but because _yum_ failed to load _libnss\_files.so_, hence it cannot parse the /etc/nsswitch.conf file, hence it cannot get _gid_ by a group name. Following is strace log about this situation

    open("/etc/nsswitch.conf", O_RDONLY)    = 31
    fstat(31, {st_mode=S_IFREG|0644, st_size=1688, ...}) = 0
    mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x2b37dd0c5000
    read(31, "#\n# /etc/nsswitch.conf\n#\n# An example Name Service Switch config file. This file should be\n# sorted with the most-used services "..., 4096) = 1688
    read(31, "", 4096)                      = 0
    close(31)                               = 0
    munmap(0x2b37dd0c5000, 4096)            = 0
    open("/etc/ld.so.cache", O_RDONLY)      = 31
    fstat(31, {st_mode=S_IFREG|0644, st_size=13800, ...}) = 0
    mmap(NULL, 13800, PROT_READ, MAP_PRIVATE, 31, 0) = 0x2b37dd0c5000
    close(31)                               = 0
    open("/lib64/tls/x86_64/libnss_files.so.2", O_RDONLY) = -1 ENOENT (No such file or directory)
    stat("/lib64/tls/x86_64", 0x7fff5524bcb0) = -1 ENOENT (No such file or directory)
    open("/lib64/tls/libnss_files.so.2", O_RDONLY) = -1 ENOENT (No such file or directory)
    stat("/lib64/tls", 0x7fff5524bcb0)      = -1 ENOENT (No such file or directory)
    open("/lib64/x86_64/libnss_files.so.2", O_RDONLY) = -1 ENOENT (No such file or directory)
    stat("/lib64/x86_64", 0x7fff5524bcb0)   = -1 ENOENT (No such file or directory)
    open("/lib64/libnss_files.so.2", O_RDONLY) = -1 ENOENT (No such file or directory)
    stat("/lib64", 0x7fff5524bcb0)          = -1 ENOENT (No such file or directory)
    open("/usr/lib64/tls/x86_64/libnss_files.so.2", O_RDONLY) = -1 ENOENT (No such file or directory)
    stat("/usr/lib64/tls/x86_64", 0x7fff5524bcb0) = -1 ENOENT (No such file or directory)
    open("/usr/lib64/tls/libnss_files.so.2", O_RDONLY) = -1 ENOENT (No such file or directory)
    stat("/usr/lib64/tls", 0x7fff5524bcb0)  = -1 ENOENT (No such file or directory)
    open("/usr/lib64/x86_64/libnss_files.so.2", O_RDONLY) = -1 ENOENT (No such file or directory)
    stat("/usr/lib64/x86_64", 0x7fff5524bcb0) = -1 ENOENT (No such file or directory)
    open("/usr/lib64/libnss_files.so.2", O_RDONLY) = -1 ENOENT (No such file or directory)
    stat("/usr/lib64", 0x7fff5524bcb0)      = -1 ENOENT (No such file or directory)

Why is _yum_ failed to load _libnss\_files.so_ library? That is because when _nscd_ running the _dynamic loader_ will not load _libnss\_files.so_, but after yum doing a chroot, in the new root filesystem, while the _nscd_ still stays alive, but  the _dynamic loader_  cannot find out _nscd_'s sock file, hence it will try to load the _libnss\_files.so_ again. But now we are in a 32bit env and  _yum_ is a process from a 64bit program, hence _yum_ search /lib64 dir instead of /lib dir.

Following are strace logs to show what we said.

When disable _nscd_

    socket(PF_FILE, SOCK_STREAM, 0)         = 6
    fcntl(6, F_SETFL, O_RDWR|O_NONBLOCK)    = 0
    connect(6, {sa_family=AF_FILE, path="/var/run/nscd/socket"...}, 110) = -1 ENOENT (No such file or directory)
    close(6)                                = 0
    socket(PF_FILE, SOCK_STREAM, 0)         = 6
    fcntl(6, F_SETFL, O_RDWR|O_NONBLOCK)    = 0
    connect(6, {sa_family=AF_FILE, path="/var/run/nscd/socket"...}, 110) = -1 ENOENT (No such file or directory)
    close(6)                                = 0
    open("/etc/nsswitch.conf", O_RDONLY)    = 6
    fstat(6, {st_mode=S_IFREG|0644, st_size=1717, ...}) = 0
    mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x2ba1350d3000
    read(6, "#\n# /etc/nsswitch.conf\n#\n# An example Name Service Switch config file. This file should be\n# sorted with the most-used services "..., 4096) = 1717
    read(6, "", 4096)                       = 0
    close(6)                                = 0
    munmap(0x2ba1350d3000, 4096)            = 0
    open("/etc/ld.so.cache", O_RDONLY)      = 6
    fstat(6, {st_mode=S_IFREG|0644, st_size=100942, ...}) = 0
    mmap(NULL, 100942, PROT_READ, MAP_PRIVATE, 6, 0) = 0x2ba1350d3000
    close(6)                                = 0
    open("/lib64/libnss_files.so.2", O_RDONLY) = 6
    read(6, "\177ELF\2\1\1\0\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0\340\37\0\0\0\0\0\0@\0\0\0\0\0\0\0x\312\0\0\0\0\0\0\0\0\0\0@\0008\0\t\0@\0 \0\37\0\6\0\0\0\5\0\0\0@\0\0\0\0\0\0\0@\0\0\0\0\0\0\0@\0\0\0\0\0\0\0\370\\
    1\0\0\0\0\0\0\370\1\0\0\0\0\0\0\10\0\0\0\0\0\0\0\3\0\0\0\4\0\0\0"..., 832) = 832
    fstat(6, {st_mode=S_IFREG|0755, st_size=53880, ...}) = 0
    mmap(NULL, 2139432, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_DENYWRITE, 6, 0) = 0x2ba1352fa000
    mprotect(0x2ba135304000, 2093056, PROT_NONE) = 0
    mmap(0x2ba135503000, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 6, 0x9000) = 0x2ba135503000
    close(6)

When enable _nscd_

    socket(PF_FILE, SOCK_STREAM, 0)         = 6                                                                                                                                                                 
    fcntl(6, F_SETFL, O_RDWR|O_NONBLOCK)    = 0                                                                                                                                                                 
    connect(6, {sa_family=AF_FILE, path="/var/run/nscd/socket"...}, 110) = 0                                                                                                                                    
    sendto(6, "\2\0\0\0\r\0\0\0\6\0\0\0hosts\0", 18, MSG_NOSIGNAL, NULL, 0) = 18                                                                                                                                
    poll([{fd=6, events=POLLIN|POLLERR|POLLHUP}], 1, 5000) = 1 ([{fd=6, revents=POLLIN}])                                                                                                                       
    recvmsg(6, {msg_name(0)=NULL, msg_iov(2)=[{"hosts\0", 6}, {"\270O\3\0\0\0\0\0", 8}], msg_controllen=24, {cmsg_len=20, cmsg_level=SOL_SOCKET, cmsg_type=SCM_RIGHTS, {7}}, msg_flags=0}, 0) = 14              
    mmap(NULL, 217016, PROT_READ, MAP_SHARED, 7, 0) = 0x2b37d5b01000                                                                                                                                            
    close(7)                                = 0                                                                                                                                                                 
    close(6)                                = 0

**Comment by xning** [comment] 2016-11-14 08:59
Such case could appear on each 64bit platform when building a 32bit package. And such case could cause trouble in some coincident situations. For example when we running _mock_ on CentOS 5, because  _yum_ still uses pipes as rpm library logger, then we could encounter a dead lock.

**Comment by xsuchy** [comment] 2016-11-14 10:31
I am really sorry. I am still confused. The warning about fakegroup is produced by whom? The strace is of which process? And inside or outside of chroot?

It will be much easier if you can provide fake.src.rpm (and steps with "mock -r") so I can test it on my own.

**Comment by xning** [comment] 2016-11-14 11:06
The waring about the fakegroup and strace logs are all from the _yum_ processes when installing _fake_ package.

**Comment by xning** [comment] 2016-11-14 11:17
@xsuchy I think you could verify the issue on an x86_64 host by following steps

1. Install and start _nscd_
2. download a mock config for i686 arch
3. mock -r yourmockconfig --init
4. mock -r youmockconfig --install tog-pegasus

**Comment by xsuchy** [comment] 2017-02-28 17:54
This is duplicate of https://bugzilla.redhat.com/show_bug.cgi?id=1118719 This need to be resolved by installing dnf/yum into temporary chroot and install final chroot using dnf/yum from the first chroot.

**Closed by xsuchy** 2017-02-28 17:54 UTC
