### ISSUE TITLE
update /etc/yum.conf, not /etc/yum/yum.conf

### ISSUE THREAD

**Issue by dkewley** [rpm-software-management/mock#82] opened 2017-06-06 03:46 UTC
I found this bug when using mock-1.3.5-1.el6.noarch from EPEL on Amazon Linux to initialize an epel-6-x86_64 chroot. It failed to initialize until I applied the following code change, because the correct file location is /etc/yum.conf, not /etc/yum/yum.conf:

```
--- package_manager.py-orig	2017-03-02 10:15:54.000000000 +0000
+++ package_manager.py	2017-06-06 03:38:13.605571068 +0000
@@ -184,7 +184,7 @@
         if os.path.exists('/usr/bin/yum-deprecated'):
             self.resolvedep_command = [
                 'repoquery', '--resolve', '--requires',
-                '--config', self.buildroot.make_chroot_path('etc', 'yum', 'yum.conf')]
+                '--config', self.buildroot.make_chroot_path('etc', 'yum.conf')]
 
     @traceLog()
     def _write_plugin_conf(self, name):
@@ -209,7 +209,7 @@
         # write in yum.conf into chroot
         # always truncate and overwrite (w+)
         self.buildroot.root_log.debug('configure yum')
-        yumconf_path = self.buildroot.make_chroot_path('etc', 'yum', 'yum.conf')
+        yumconf_path = self.buildroot.make_chroot_path('etc', 'yum.conf')
         with open(yumconf_path, 'w+') as yumconf_file:
             yumconf_file.write(config_content)
```

The bug is also in the devel and master branches. This is my first time using mock, so I don't know why it doesn't work for me but must be working in other contexts.

**Comment by xsuchy** [comment] 2017-06-06 06:46
That is strange. According this code:
```
        # If the conf file is inside the  installroot - use that.
        # otherwise look for it in the normal root
        if opts.installroot and opts.installroot.lstrip('/'):
            if os.access(opts.installroot+'/'+opts.conffile, os.R_OK):                                                                                
                opts.conffile = opts.installroot+'/'+opts.conffile
            elif opts.conffile == '/etc/yum/yum.conf':
                # check if /installroot/etc/yum.conf exists.
                if os.access(opts.installroot+'/etc/yum.conf', os.R_OK):
                    opts.conffile = opts.installroot+'/etc/yum.conf'
            root=opts.installroot
```

yum uses `/etc/yum/yum.conf` and only if it does not exists it will use `/etc/yum.conf`. Can you post exact steps to reproduce and error you get (without this patch applied)?

**Comment by dkewley** [comment] 2017-06-06 19:26
I've found that CentOS6 prefers /etc/yum/yum.conf and if it doesn't exist falls back to /etc/yum.conf, as in the code you showed (even though the yum.conf man page was patched in CentOS 6 to say to use /etc/yum.conf). Amazon Linux does the reverse in their yum package: prefer /etc/yum.conf, and fall back to /etc/yum/yum.conf.

Mock touches /etc/yum.conf, but leaves it empty. It copies the 'yum.conf' config option's contents into /etc/yum/yum.conf. CentOS6 successfully uses the populated /etc/yum/yum.conf, but Amazon Linux uses the empty /etc/yum.conf and fails.

Here's a simpler patch that I've confirmed does work in Amazon Linux as a mock host:

`--- /usr/lib/python2.6/site-packages/mockbuild/package_manager.py-orig	2017-03-02 10:15:54.000000000 +0000
+++ /usr/lib/python2.6/site-packages/mockbuild/package_manager.py	2017-06-06 19:08:52.070397770 +0000
@@ -212,6 +212,9 @@
         yumconf_path = self.buildroot.make_chroot_path('etc', 'yum', 'yum.conf')
         with open(yumconf_path, 'w+') as yumconf_file:
             yumconf_file.write(config_content)
+        yumconf_path = self.buildroot.make_chroot_path('etc', 'yum.conf')
+        with open(yumconf_path, 'w+') as yumconf_file:
+            yumconf_file.write(config_content)
 
         # write in yum plugins into chroot
         self.buildroot.root_log.debug('configure yum priorities')
`

This worked for me on Amazon Linux. I didn't test on CentOS6, but I *think* it wouldn't break there. At your option you could make a symbolic or hard link -- it seems like that should work too.

If you decline to support Amazon Linux in this way, I think that might be OK. A simple fallback for me was to use CentOS6 for my EC2 build machine. I don't yet see a significant advantage to using Amazon Linux as a build host, versus using a CentOS6 AMI. If you choose to go this route, I'd only ask that you consider documenting the advice to use a CentOS AMI somewhere relevant before you close this issue.

FWIW, Amazon Linux ships with EPEL 6 configured in /etc/yum.repos.d/, but simply disabled. So building for CentOS 6 is indeed what we care about on Amazon Linux.

**Comment by xsuchy** [comment] 2017-06-08 10:00
Fixed by creating symlink instead of just touching. You may need scrub you mock cache thou if you want use it, because if /etc/yum.conf exists the symlink cannot be created.

**Closed by xsuchy** 2017-06-08 10:00 UTC
