### ISSUE TITLE
`Curl error (6): Couldn't resolve host name` within Fedora 35 mock buidlroot on CentOS 8 Linux host

### ISSUE THREAD

**Issue by anoopcs9** [rpm-software-management/mock#811] opened 2021-11-26 07:34 UTC
### Short description of the problem
On a CentOS 8 Linux host, Fedora 35 mock buildoort fails to setup during package repository sync with following error:
```
fedora                                                                                                                         0.0  B/s |   0  B     00:00    
Errors during downloading metadata for repository 'fedora':
  - Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=fedora-35&arch=x86_64 [getaddrinfo() thread failed to start]
Error: Failed to download metadata for repo 'fedora': Cannot prepare internal mirrorlist: Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=fedora-35&arch=x86_64 [getaddrinfo() thread failed to start]
ERROR: Command failed: 
 # /usr/bin/systemd-nspawn -q -M 406e5be982ab4cfa8455da19e7774eda -D /var/lib/mock/fedora-35-x86_64-bootstrap/root -a --capability=cap_ipc_lock --bind=/tmp/mock-resolv.wu_fyfix:/etc/resolv.conf --setenv=TERM=vt100 --setenv=SHELL=/bin/bash --setenv=HOME=/var/lib/mock/fedora-35-x86_64/root/installation-homedir --setenv=HOSTNAME=mock --setenv=PATH=/usr/bin:/bin:/usr/sbin:/sbin --setenv=PROMPT_COMMAND=printf "\033]0;<mock-chroot>\007" --setenv=PS1=<mock-chroot> \s-\v\$  --setenv=LANG=C.UTF-8 --setenv=LC_MESSAGES=C.UTF-8 --resolv-conf=off /usr/bin/dnf --installroot /var/lib/mock/fedora-35-x86_64/root/ --releasever 35 --setopt=deltarpm=False --allowerasing --disableplugin=local --disableplugin=spacewalk --disableplugin=versionlock install @buildsys-build --setopt=tsflags=nocontexts
No matches found for the following disable plugin patterns: local, spacewalk, versionlock
fedora                                                                                                                         0.0  B/s |   0  B     00:00    
Errors during downloading metadata for repository 'fedora':
  - Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=fedora-35&arch=x86_64 [getaddrinfo() thread failed to start]
Error: Failed to download metadata for repo 'fedora': Cannot prepare internal mirrorlist: Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=fedora-35&arch=x86_64 [getaddrinfo() thread failed to start]
```
### Output of `rpm -q mock`
mock-2.14-1.el8.noarch

### Steps to reproduce issue

1. Have a CentOS 8 Linux host
2. Install mock
3. Run `mock -r fedora-35-x86_64 --scrub=all; mock -r fedora-35-x86_64 init`

### Any additional notes
Workaround is to use _simple_ isolation mechanism different from default systemd-nspawn container mechanism.

**Comment by praiskup** [comment] 2021-11-26 08:38
OK, reproduced on RHEL 8 box. This seems to be a bug somewhere in systemd-nspawn, I think.
The resolv.conf is correctly set, podman just works.  Can this again be the syscall filtering mechanism?

**Comment by praiskup** [comment] 2021-11-26 08:39
Podman "just works".

**Comment by anoopcs9** [comment] 2021-11-26 09:47
> I think that I found the related [systemd-nspawn bug](https://bugzilla.redhat.com/show_bug.cgi?id=1992708).

Great. Yesterday I managed to find similar [bugzilla report](https://bugzilla.redhat.com/show_bug.cgi?id=2007758) after IRC discussion.

I can also confirm that adding `--system-call-filter=clone3` to _systemd-nspawn_ is another workaround to the problem as it is the syscall which is currently not present in the whitelist.
```
# /usr/bin/systemd-nspawn -q  -D /var/tmp/f35-root -a --system-call-filter=clone3 --capability=cap_ipc_lock --bind=/etc/resolv.conf:/etc/resolv.conf --setenv=SHELL=/bin/bash --setenv=LC_MESSAGES=C.UTF-8 --resolv-conf=off bash
bash-5.1# curl https://fedoraproject.org
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>302 Found</title>
</head><body>
<h1>Found</h1>
<p>The document has moved <a href="https://getfedora.org/">here</a>.</p>
<hr>
<address>Apache Server at fedoraproject.org Port 443</address>
</body></html>
```

**Comment by praiskup** [comment] 2021-12-13 14:28
I removed myself from this issue, we are just tracking the systemd issue here that
hopefully will be fixed soon.

**Comment by anoopcs9** [comment] 2021-12-14 13:44
Adding some more details:

Even though _glibc_ started using `clone3()` syscall with newer versions, default allow-list for systemd-nspwan's seccomp filter didn't have it included as part of `@process` set. This set within _systemd_ was [updated](https://github.com/systemd/systemd/commit/9e486265716963439fb0fd7f2a97abf109f24f75) to include `clone3()`(with 5.3 kernel release) and is available from v244. But _systemd_ version on CentOS 8 doesn't have the change included and thus EPERM is returned instead of ENOSYS. _glibc_ can only fallback to `clone()` on receiving ENOSYS.

On Fedora 35:
```
$ sudo systemd-analyze syscall-filter | grep clone3
    clone3
    clone3
```

On CentOS 8:
```
# systemd-analyze syscall-filter | grep clone3
```

Therefore I doubt whether _systemd_ will get updated with this change on CentOS 8.

**Comment by praiskup** [comment] 2021-12-16 14:58
Hm, I thus fail to understand what we should do here.  Does that mean that we should
fallback to --isolation=simple on EL8 anytime we build for Fedora >= N?

**Comment by praiskup** [comment] 2021-12-16 15:35
So what about to disable the syscall filtering, see #835?

**Closed** 2021-12-16 16:40 UTC
Labels: nspawn

**Comment by anoopcs9** [comment] 2021-12-16 17:58
> So what about to disable the syscall filtering, see #835?

That's another workaround I forgot to mention previously. And I see that the change is already merged.
Thanks for the patch. When can I expect next mock release with the systemd workaround?

**Comment by sej7278** [comment] 2021-12-30 16:41
is there an ETA for the fixed version of mock to hit EPEL8?

I've had the same failure building anything on centos stream 8 (cs9, f36, rhel8, cs8.....) using mock-2.15-1.el8.noarch from november 18th.

**Comment by anoopcs9** [comment] 2021-12-31 05:18
> is there an ETA for the fixed version of mock to hit EPEL8?

Due to some other issues updates are still at testing phase. For more details refer [FEDORA-EPEL-2021-2d0f959e00](https://bodhi.fedoraproject.org/updates/FEDORA-EPEL-2021-2d0f959e00).

**Comment by praiskup** [comment] 2021-12-31 08:23
Yes, please try `dnf update mock --enablerepo epel-testing`.  The mock Bodhi updates are blocked by an issue that can not be fixed in mock, so it may take time till the updated package gets to the stable repo.
