### ISSUE TITLE
use_nspawn + --cwd option

### ISSUE THREAD

**Issue by owtaylor** [rpm-software-management/mock#108] opened 2017-08-17 20:50 UTC
If USE_NSPAWN is true, then the cwd option is passed to systemd-nspawn, but the code *also* tries to chdir in  utils.ChildPreExec.__call__() - this fails because the cwd is relative to the chroot and we haven't yet done the chroot. The condChdir() should be part of the 'if not USE_NSPAWN' block. 

https://github.com/rpm-software-management/mock/blob/ef5e8499a57a960eb6d6505365540c0404c2dbc5/py/mockbuild/util.py#L617

**Comment by xsuchy** [comment] 2017-08-22 12:55
Can you please provide the reproducer? I cannot reproduce it. By pure reading of the code I think you are right, but I would like to reproduce the fail first to be sure.

**Comment by owtaylor** [comment] 2017-08-22 13:26
I think the tricky thing about reproducing it is that if you pass a directory that also exists on the host to --cwd, the extra chdir is harmless, but you can reproduce with:

    mock -r fedora-26-x86_64 --chroot mkdir /mnt/not-on-host
    mock -r fedora-26-x86_64 --cwd /mnt/not-on-host --chroot ls

That fails with `subprocess.SubprocessError: Exception occurred in preexec_fn`. If I move the condChdir inside the block, it works.

**Comment by xsuchy** [comment] 2017-12-13 12:59
Fixed in commit
* a40567a (HEAD -> devel, origin/devel, origin/HEAD) do not cd to dir if nspawn is used [GH#108]

Thank you for the investigation and the report.

**Closed by xsuchy** 2017-12-13 12:59 UTC
Labels: bug
