### ISSUE TITLE
Add default route to `lo` in container when network is disabled

### ISSUE THREAD

**Issue by junaruga** [rpm-software-management/mock#113] opened 2017-08-28 13:09 UTC
`ruby.spec` has a test for ipv4 multicast on mock environment.
I want to enable the multicast for `enp0s25` (ipv4) network interface in mock.

But when I tested with `ip` command to check it on mock, the process during check section, `enp0s25` multicast was still disabled.
Then when I did `mock --shell`, the multicast was enabled.
Do you have any idea to enable the multicast for the process of check section?

```
$ git diff ruby.spec

+BuildRequires: /usr/sbin/ip

-make check TESTS="-v $DISABLE_TESTS"
+sleep 30
+ip maddress
+make test-all TESTS="rinda/test_rinda.rb"
```

```
$ fedpkg srpm
$ mock -r fedora-rawhide-x86_64 *.rpm
```

build.log (https://gist.github.com/junaruga/c6e25d26b09ab89115ad64fa44274763)
```
+ sleep 30
+ ip maddress <= only lo's multicast is enabled.
1:  lo 
    inet  224.0.0.1
    inet6 ff02::1
    inet6 ff01::1
+ make test-all TESTS=rinda/test_rinda.rb
=> Errror
```

```
$ mock -r fedora-rawhide-x86_64 --shell

<mock-chroot> sh-4.4# ip maddress
1:	lo
	inet  224.0.0.1
	inet6 ff02::1
	inet6 ff01::1
2:	enp0s25
	link  01:00:5e:00:00:01
	inet  224.0.0.1
	inet6 ff02::1
	inet6 ff01::1
...
```

**Comment by ignatenkobrain** [comment] 2017-08-28 13:17
I guess this problem tightly related to using systemd-nspawn.. cc @msekletar

**Comment by junaruga** [comment] 2017-08-28 15:00
@ignatenkobrain Maybe that's right.
I could build with `mock --old-chroot` option (use old chroot instead of systemd-nspawn), and multicast is enabled on the mock.

```
$ mock -r fedora-rawhide-x86_64 --old-chroot *.rpm
...
+ sleep 30
+ ip maddress
1:  lo
    inet  224.0.0.1
    inet6 ff02::1
    inet6 ff01::1
2:  enp0s25
    link  01:00:5e:00:00:01
    inet  224.0.0.1
    inet6 ff02::1
    inet6 ff01::1
...
```
=> Success

**Comment by xsuchy** [comment] 2017-08-28 15:21
I have no idea how multicasts work in systemd-nspawn. I am trying to avoid any network related tasks in spec files.

**Comment by junaruga** [comment] 2017-08-29 08:06
@xsuchy okay. As a reference, I am using below systemd-container.

```
$ rpm -qf /usr/bin/systemd-nspawn
systemd-container-231-17.fc25.x86_64
```

**Comment by junaruga** [comment] 2017-08-29 09:06
I tried below both cases, and the situation is same for both.

```
config_opts['use_host_resolv'] = False or True
```

However my colleague succeeded to build Fedora ruby for both `--old-chroot` and `--new-chroot` without the errors today. So, my local environment might be wrong.

His installed systemd-nspawn is as follows. 

```
$ rpm -qf /usr/bin/systemd-nspawn
systemd-container-234-5.fc27.x86_64
```

**Comment by junaruga** [comment] 2017-08-29 11:14
The problem solved by the colleague's help.

I added below option and the build was succeeded.
The multicast was enabled in systemd-nspawn environment.

```
$ vi ~/.config/mock.cfg 

# To test multicast on mock (systemd-nspawn).
config_opts['rpmbuild_networking'] = True
```

```
$ mock -r fedora-rawhide-x86_64 *.rpm

+ DISABLE_TESTS=' -x test_fork.rb'
+ ip maddress
1:  lo 
    inet  224.0.0.1
    inet6 ff02::1
    inet6 ff01::1
2:  enp0s25
    link  01:00:5e:00:00:01
    link  33:33:00:00:00:01
    inet  224.0.0.1
    inet6 ff02::1
    inet6 ff01::1
...
+ make test-all TESTS=rinda/test_rinda.rb
...
39 tests, 396 assertions, 0 failures, 0 errors, 0 skips
```

I think this option can be set in `/etc/mock/*.cfg` as initial settings.

Or 

We can update document for that.
https://fedoraproject.org/wiki/Using_Mock_to_test_package_builds

Thanks.

**Comment by xsuchy** [comment] 2017-08-29 12:30
It is already documented here. https://github.com/rpm-software-management/mock/blob/devel/etc/mock/site-defaults.cfg#L59

By default, all rpms should be build without network access (that is Koji default as well). So it is OK to have it disabled by default.

As it is working for you now, I am closing this.

**Comment by msekletar** [comment] 2017-08-29 13:19
FWIW, failing multicast subscription in ```test_rinda.rb``` is caused by missing default route in nspawn container.

**Comment by junaruga** [comment] 2017-08-29 14:01
@xsuchy 

> It is already documented here. https://github.com/rpm-software-management/mock/blob/devel/etc/mock/site-defaults.cfg#L59
> 
> By default, all rpms should be build without network access (that is Koji default as well). So it is OK to have it disabled by default.
> 
> As it is working for you now, I am closing this.

I am fine to close this ticket. Thanks.
I could build, enabling multicast by enabling `config_opts['rpmbuild_networking'] = True
`.
But I think this is not a right way.

Because ruby's test should be passed without network access.
Look at below Koji build by "$ fedpkg scratch-build --srpm" that I ran right now.
The build is passing with multicast.

https://koji.fedoraproject.org/koji/taskinfo?taskID=21528597
x86_64: https://kojipkgs.fedoraproject.org//work/tasks/8598/21528598/build.log

```
+ ip maddress
1:	lo
	inet  224.0.0.1
	inet6 ff02::1
	inet6 ff01::1
2:	eth0
	link  01:00:5e:00:00:01
	link  33:33:00:00:00:01
	link  33:33:ff:dd:ec:96
	inet  224.0.0.1
	inet6 ff02::1:ffdd:ec96
	inet6 ff02::1
	inet6 ff01::1
...
+ make test-all TESTS=rinda/test_rinda.rb
...
39 tests, 396 assertions, 0 failures, 0 errors, 0 skips
```


@msekletar 

> FWIW, failing multicast subscription in test_rinda.rb is caused by missing default route in nspawn container.

What is "missing default route in nspawn container"?
Is it my local environment's issue? or the upstream "nspawn container" program's issue?

**Comment by xsuchy** [comment] 2017-08-29 15:12
After talking to @msekletar I am reopening this issue. The container is missing default route (to loopback device) Therefore kernel does not know which network device to choose to multicast.

We should add the logic: if $container and $network_disabled then ip route add default gw lo

Of course, we need to do that from host using -netns as 'ip' command is not available in the container.

**Comment by voxik** [comment] 2017-09-04 13:48
I reported this to Ruby upstream [[1]]. Will see what's their opinion.

[1]: https://bugs.ruby-lang.org/issues/13864

**Comment by xsuchy** [comment] 2017-09-04 16:11
Notes from @msekletar  how to add default route

```
#!/bin/bash
container=$1

# setup
mkdir -p /run/netns
eval $(machinectl show -p Leader ${container})
touch /run/netns/ns-pid-${Leader}
mount --bind /proc/${Leader}/ns/net /run/netns/ns-pid-${Leader}

# add route
ip netns exec ns-pid-${Leader} ip route add default via 127.0.0.1

# clean up
umount /run/netns/ns-pid-${Leader}
rm -f /run/netns/ns-pid-${Leader}
```

**Closed** 2017-10-02 07:26 UTC
