### ISSUE TITLE
mock 5.0 broke runroot tasks in ODCS

### ISSUE THREAD

**Issue by sgallagher** [rpm-software-management/mock#1188] opened 2023-08-21 12:23 UTC
### Short description of the problem

See https://koji.fedoraproject.org/koji/taskinfo?taskID=105065831

```
2023-08-21 08:03:14,674 [INFO] {176624} koji.build.buildroot:564 Running mock as kojibuilder
ERROR: Option --new-chroot has been deprecated. Use --isolation=nspawn instead.
INFO: mock.py version 5.0 starting (python version = 3.11.4, NVR = mock-5.0-1.fc38)...
Start(bootstrap): init plugins
INFO: selinux enabled
Finish(bootstrap): init plugins
Start: init plugins
INFO: selinux enabled
Finish: init plugins
INFO: Signal handler active
Start: run
Mock Version: 5.0
INFO: Mock Version: 5.0
Start(bootstrap): chroot init
INFO: calling preinit hooks
INFO: Package manager dnf detected and used (fallback)
Finish(bootstrap): chroot init
Start: chroot init
INFO: calling preinit hooks
INFO: enabled HW Info plugin
Traceback (most recent call last):
  File "/usr/libexec/mock/mock", line 1087, in <module>
    exitStatus = main()
                 ^^^^^^
  File "/usr/lib/python3.11/site-packages/mockbuild/trace_decorator.py", line 93, in trace
    result = func(*args, **kw)
             ^^^^^^^^^^^^^^^^^
  File "/usr/libexec/mock/mock", line 847, in main
    result = run_command(options, args, config_opts, commands, buildroot, state)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/mockbuild/trace_decorator.py", line 93, in trace
    result = func(*args, **kw)
             ^^^^^^^^^^^^^^^^^
  File "/usr/libexec/mock/mock", line 902, in run_command
    commands.init(do_log=True)
  File "/usr/lib/python3.11/site-packages/mockbuild/trace_decorator.py", line 93, in trace
    result = func(*args, **kw)
             ^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/mockbuild/backend.py", line 167, in init
    self.buildroot.initialize(**kwargs)
  File "/usr/lib/python3.11/site-packages/mockbuild/trace_decorator.py", line 93, in trace
    result = func(*args, **kw)
             ^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/mockbuild/buildroot.py", line 186, in initialize
    self._init(prebuild=prebuild)
  File "/usr/lib/python3.11/site-packages/mockbuild/trace_decorator.py", line 93, in trace
    result = func(*args, **kw)
             ^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/mockbuild/buildroot.py", line 241, in _init
    self._setup_devices()
  File "/usr/lib/python3.11/site-packages/mockbuild/trace_decorator.py", line 93, in trace
    result = func(*args, **kw)
             ^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/mockbuild/buildroot.py", line 765, in _setup_devices
    os.mknod(chroot_path, i[0], i[1])
FileExistsError: [Errno 17] File exists
```

### Output of `rpm -q mock`

mock-5.0-1.fc38

### Steps to reproduce issue

Run a compose using ODCS

### Any additional notes

This is currently preventing all Fedora ELN composes from running.

**Comment by praiskup** [comment] 2023-08-22 09:13
Thank you for the report.  Weird, off-hand I'd say nothing has changed here.  Can you confirm that downgrading back to Mock 4.X helps?

**Comment by sgallagher** [comment] 2023-08-22 12:55
Yes, a downgrade works immediately.

**Comment by praiskup** [comment] 2023-09-07 11:44
@sgallagher don't you have full logs here?  Is this s390x only?  Is the overlay Mock plugin in action?  What is the device file that raises `File exists`?

**Comment by praiskup** [comment] 2023-09-07 11:54
I suspect this patch 836509e0e61458e3168eb174fdc1585ec571de4a

**Comment by sgallagher** [comment] 2023-09-07 14:51
I need to redirect these questions to @nirik

**Comment by nirik** [comment] 2023-09-07 21:26
We are using 'config_opts['use_bootstrap_image'] = False' as mock 5.0 landed right before beta freeze and builders were not allowed to access registry, so we just disabled it until we had a chance to adjust things. Also, it will probibly never work on s390x as those are in another datacenter with very restricted internet access. :(

It might have affected other than s390x, I am not sure... we can try again after freeze to see fully what happens if someone can remind me to do so.

**Comment by praiskup** [comment] 2023-09-08 04:42
Oh, [I did not even expect](https://github.com/rpm-software-management/mock/pull/1101#issuecomment-1638038001) we would start using the bootstrap image feature in Koji since day 1!  Thank you for testing it.  I think we could have some cache mechanism / local registry, custom on-builder cached images (if Mock can not pull the image, it [doesn't fail](https://github.com/rpm-software-management/mock/blob/49c9cb6014e47ead6ab764de7ccadec1bb2b4404/mock/py/mockbuild/podman.py#L79) and tries to use local cache), etc.  Feel free to open corresponding issues if there's anything we could help with in Mock.

What about the original traceback?  Was that just some weird failure that you successfully resolved, or is it reproducible now?

**Comment by nirik** [comment] 2023-09-08 16:23
I can try and gather more information after beta freeze by re-upgrading.

**Comment by praiskup** [comment] 2023-09-25 08:37
@nirik would you mind chekcing Mock 5.1.1 now?  I'd like to release Mock 5.2 ASAP because of #1233 and it is a good chance to have ODCS problem fixed, too.

**Comment by nirik** [comment] 2023-09-25 16:58
5.1.1 seems to still fail: 

https://koji.fedoraproject.org/koji/taskinfo?taskID=106693054

```
Traceback (most recent call last):
  File "/usr/libexec/mock/mock", line 1071, in <module>
    exitStatus = main()
                 ^^^^^^
  File "/usr/lib/python3.11/site-packages/mockbuild/trace_decorator.py", line 93, in trace
    result = func(*args, **kw)
             ^^^^^^^^^^^^^^^^^
  File "/usr/libexec/mock/mock", line 831, in main
    result = run_command(options, args, config_opts, commands, buildroot, state)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/mockbuild/trace_decorator.py", line 93, in trace
    result = func(*args, **kw)
             ^^^^^^^^^^^^^^^^^
  File "/usr/libexec/mock/mock", line 909, in run_command
    commands.init()
  File "/usr/lib/python3.11/site-packages/mockbuild/trace_decorator.py", line 93, in trace
    result = func(*args, **kw)
             ^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/mockbuild/backend.py", line 167, in init
    self.buildroot.initialize(**kwargs)
  File "/usr/lib/python3.11/site-packages/mockbuild/trace_decorator.py", line 93, in trace
    result = func(*args, **kw)
             ^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/mockbuild/buildroot.py", line 198, in initialize
    self._init(prebuild=prebuild)
  File "/usr/lib/python3.11/site-packages/mockbuild/trace_decorator.py", line 93, in trace
    result = func(*args, **kw)
             ^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/mockbuild/buildroot.py", line 293, in _init
    self._setup_devices()
  File "/usr/lib/python3.11/site-packages/mockbuild/trace_decorator.py", line 93, in trace
    result = func(*args, **kw)
             ^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/mockbuild/buildroot.py", line 817, in _setup_devices
    os.mknod(chroot_path, i[0], i[1])
FileExistsError: [Errno 17] File exists
```

**Comment by praiskup** [comment] 2023-09-26 08:39
@nirik is this because `/dev/fuse` exists? Caused by 836509e0e61458e3168eb174fdc1585ec571de4a?

**Comment by praiskup** [comment] 2023-09-26 13:12
@nirik I grepped Infra's ansible repo, and found [this config](https://pagure.io/fedora-infra/ansible/blob/f96e86c09509bd7cf8ec34e5df88214604690c09/f/roles/koji_builder/templates/builders/site-defaults.cfg#_18-19):

    config_opts['plugin_conf']['bind_mount_opts']['dirs'].append(("/dev/fuse", "/dev/fuse"))
    config_opts['nspawn_args'] += ['--bind=/dev/fuse']

It is fighting with the [Mock's built-in ](https://github.com/rpm-software-management/mock/pull/1158)`/dev/fuse` copy logic.

**Comment by nirik** [comment] 2023-09-26 18:59
Ah ha. Yes, that might do it. 

Ok, let me try removing that (which we added for ostree oci images) and see if it works then.

**Comment by nirik** [comment] 2023-09-27 16:07
Looks like that was it. 5.1.1 worked for eln composes. ;) 

I will likely update all the builders later today and let you know if I see any issues... thanks for the fixes!

**Comment by praiskup** [comment] 2023-10-01 19:32
I've seen 5.1.1 in Koji production.  It does work well eventually, I bet.  Closing.

**Closed by praiskup** 2023-10-01 19:32 UTC
