### ISSUE TITLE
Make 'dnf' in 'mock -r rhel-X-x86_64 --enable-network --shell' work

### ISSUE THREAD

**Issue by praiskup** [rpm-software-management/mock#1002] opened 2022-11-08 14:06 UTC
Even though I have a subscription taken on host, I can't easily debug DNF from within a RHEL chroot:
```
$ mock -r rhel-8-x86_64 --install dnf subscription-manager
// ... let it install ...
$ mock -r rhel-8-x86_64 --shell --enable-network
...
<mock-chroot> sh-4.4# dnf module list
Updating Subscription Management repositories.
Unable to read consumer identity

This system is not registered with an entitlement server. You can use subscription-manager to register.

Red Hat Enterprise Linux - BaseOS                                                                                                                                                                           0.0  B/s |   0  B     00:00    
Errors during downloading metadata for repository 'rhel-baseos':
  - Curl error (58): Problem with the local SSL certificate for https://cdn.redhat.com/content/dist/rhel8/8/x86_64/baseos/os/repodata/repomd.xml [could not load PEM client certificate, OpenSSL error error:02001002:system library:fopen:No such file or directory, (no key found, wrong pass phrase, or wrong file format?)]
Error: Failed to download metadata for repo 'rhel-baseos': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried
```

**Comment by xsuchy** [comment] 2022-12-16 22:23
This is a duplicate of 
https://github.com/rpm-software-management/mock/issues/444

**Closed by xsuchy** 2022-12-16 22:23 UTC
Labels: enhancement
