### ISSUE TITLE
git clone fails into mock

### ISSUE THREAD

**Issue by kuboosoft** [rpm-software-management/mock#86] opened 2017-06-16 16:05 UTC
I need clean a source code, but when I make a "git clone ....." show the next error, My internet connection works perfectly... Making a "mock -r fedora-25-x86_64 -shell" git, cloned without problem; But using Mock outside my git sandbox fails...

Fedora 26 x66_64
```
Mock Version: 1.4.1
ENTER ['do'](['/usr/bin/rpmbuild', '-bs', '--target', 'x86_64', '--nodeps', '/builddir/build/SPECS/vlc.spec'], chrootPath='/var/lib/mock/fedora-25-x86_64/root'env={'TERM': 'vt100', 'SHELL': '/bin/bash', 'HOME': '/builddir', 'HOSTNAME': 'mock', 'PATH': '/usr/bin:/bin:/usr/sbin:/sbin', 'PROMPT_COMMAND': 'printf "\\033]0;<mock-chroot>\\007"', 'PS1': '<mock-chroot> \\s-\\v\\$ ', 'LANG': 'es_GT.UTF-8'}shell=Falselogger=<mockbuild.trace_decorator.getLog object at 0x7f6f6ddb14a8>timeout=0uid=1001gid=135user='mockbuild'nspawn_args=[]printOutput=True)
Executing command: ['/usr/bin/systemd-nspawn', '-q', '-M', '39a2960ce0b44d06ba3363d7d2becdbd', '-D', '/var/lib/mock/fedora-25-x86_64/root', '-a', '--setenv=TERM=vt100', '--setenv=SHELL=/bin/bash', '--setenv=HOME=/builddir', '--setenv=HOSTNAME=mock', '--setenv=PATH=/usr/bin:/bin:/usr/sbin:/sbin', '--setenv=PROMPT_COMMAND=printf "\\033]0;<mock-chroot>\\007"', '--setenv=PS1=<mock-chroot> \\s-\\v\\$ ', '--setenv=LANG=es_GT.UTF-8', '-u', 'mockbuild', '/usr/bin/rpmbuild', '-bs', '--target', 'x86_64', '--nodeps', '/builddir/build/SPECS/vlc.spec'] with env {'TERM': 'vt100', 'SHELL': '/bin/bash', 'HOME': '/builddir', 'HOSTNAME': 'mock', 'PATH': '/usr/bin:/bin:/usr/sbin:/sbin', 'PROMPT_COMMAND': 'printf "\\033]0;<mock-chroot>\\007"', 'PS1': '<mock-chroot> \\s-\\v\\$ ', 'LANG': 'es_GT.UTF-8'} and shell False
Construyendo las plataformas de destino: x86_64
Construyendo para el destino x86_64
Escrito: /builddir/build/SRPMS/vlc-3.0.0-37.git86f6ef1.fc25.src.rpm
Child return code was: 0
ENTER ['do'](['/usr/bin/rpmbuild', '-bb', '--target', 'x86_64', '--nodeps', '/builddir/build/SPECS/vlc.spec'], chrootPath='/var/lib/mock/fedora-25-x86_64/root'env={'TERM': 'vt100', 'SHELL': '/bin/bash', 'HOME': '/builddir', 'HOSTNAME': 'mock', 'PATH': '/usr/bin:/bin:/usr/sbin:/sbin', 'PROMPT_COMMAND': 'printf "\\033]0;<mock-chroot>\\007"', 'PS1': '<mock-chroot> \\s-\\v\\$ ', 'LANG': 'es_GT.UTF-8'}shell=Falselogger=<mockbuild.trace_decorator.getLog object at 0x7f6f6ddb14a8>timeout=0uid=1001gid=135user='mockbuild'nspawn_args=['--private-network']printOutput=True)
Executing command: ['/usr/bin/systemd-nspawn', '-q', '-M', '50c69020ef8e4e82b0f142d3e2e2a123', '-D', '/var/lib/mock/fedora-25-x86_64/root', '-a', '--private-network', '--setenv=TERM=vt100', '--setenv=SHELL=/bin/bash', '--setenv=HOME=/builddir', '--setenv=HOSTNAME=mock', '--setenv=PATH=/usr/bin:/bin:/usr/sbin:/sbin', '--setenv=PROMPT_COMMAND=printf "\\033]0;<mock-chroot>\\007"', '--setenv=PS1=<mock-chroot> \\s-\\v\\$ ', '--setenv=LANG=es_GT.UTF-8', '-u', 'mockbuild', '/usr/bin/rpmbuild', '-bb', '--target', 'x86_64', '--nodeps', '/builddir/build/SPECS/vlc.spec'] with env {'TERM': 'vt100', 'SHELL': '/bin/bash', 'HOME': '/builddir', 'HOSTNAME': 'mock', 'PATH': '/usr/bin:/bin:/usr/sbin:/sbin', 'PROMPT_COMMAND': 'printf "\\033]0;<mock-chroot>\\007"', 'PS1': '<mock-chroot> \\s-\\v\\$ ', 'LANG': 'es_GT.UTF-8'} and shell False
Construyendo las plataformas de destino: x86_64
Construyendo para el destino x86_64
Ejecutando(%prep): /bin/sh -e /var/tmp/rpm-tmp.GbY6Wq
+ umask 022
+ cd /builddir/build/BUILD
+ /builddir/build/SOURCES/vlc-snapshot -c 86f6ef18909e496ead084bab13fb6f5f0b968d07
Cloning into 'vlc-86f6ef1'...
fatal: unable to access 'https://github.com/videolan/vlc.git/': Could not resolve host: github.com
/builddir/build/SOURCES/vlc-snapshot: line 39: pushd: vlc-86f6ef1: No such file or directory
fatal: Not a git repository (or any of the parent directories): .git
/builddir/build/SOURCES/vlc-snapshot: line 41: popd: directory stack empty
tar: vlc-86f6ef1: Cannot stat: No such file or directory
tar: Exiting with failure status due to previous errors
Errores de construcción RPM:
error: Estado de salida erróneo de /var/tmp/rpm-tmp.GbY6Wq (%prep)
    Estado de salida erróneo de /var/tmp/rpm-tmp.GbY6Wq (%prep)
Child return code was: 1
EXCEPTION: [Error()]
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/mockbuild/trace_decorator.py", line 96, in trace
    result = func(*args, **kw)
  File "/usr/lib/python3.6/site-packages/mockbuild/util.py", line 590, in do
    raise exception.Error("Command failed: \n # %s\n%s" % (command, output), child.returncode)
mockbuild.exception.Error: Command failed: 
 # /usr/bin/systemd-nspawn -q -M 50c69020ef8e4e82b0f142d3e2e2a123 -D /var/lib/mock/fedora-25-x86_64/root -a --private-network --setenv=TERM=vt100 --setenv=SHELL=/bin/bash --setenv=HOME=/builddir --setenv=HOSTNAME=mock --setenv=PATH=/usr/bin:/bin:/usr/sbin:/sbin --setenv=PROMPT_COMMAND=printf "\033]0;<mock-chroot>\007" --setenv=PS1=<mock-chroot> \s-\v\$  --setenv=LANG=es_GT.UTF-8 -u mockbuild /usr/bin/rpmbuild -bb --target x86_64 --nodeps /builddir/build/SPECS/vlc.spec
```

**Comment by Frodox** [comment] 2017-06-16 17:43
Well, there is no internet setup inside [systemd container I think out of box](https://github.com/rpm-software-management/mock/blob/46596dfd425a5bac58f51029fdd8c620623e4bb4/etc/mock/site-defaults.cfg#L64)

> fatal: unable to access 'https://github.com/videolan/vlc.git/': Could not resolve host: github.com

try to run it with
```
config_opts['rpmbuild_networking'] = True
```
if fail, then with
```
config_opts['use_nspawn'] = False
config_opts['use_bootstrap_container'] = False
```

it would be cool to see full command you used (for tests)

**Comment by kuboosoft** [comment] 2017-06-16 20:03
the config mock for F26 is virgin... I do not touch nothing here :/

```
config_opts['root'] = 'fedora-26-x86_64'
config_opts['target_arch'] = 'x86_64'
config_opts['legal_host_arches'] = ('x86_64',)
config_opts['chroot_setup_cmd'] = 'install @buildsys-build'
config_opts['dist'] = 'fc26'  # only useful for --resultdir variable subst
config_opts['extra_chroot_dirs'] = [ '/run/lock', ]
config_opts['releasever'] = '26'
config_opts['package_manager'] = 'dnf'
```
Great!  **config_opts['rpmbuild_networking'] = True** solved the issue; why the macro is missed in F26 mock? in F25 works fine...

**Comment by Frodox** [comment] 2017-06-16 20:27
It is not *missed*, it is official feature *for more reproducible builds*. Take a look in site-default.cfg: https://github.com/rpm-software-management/mock/blob/46596dfd425a5bac58f51029fdd8c620623e4bb4/etc/mock/site-defaults.cfg#L64

```
# By default Mock use simple chroot(1). When you set this to True
# it will use systemd-nspawn(1)
# config_opts['use_nspawn'] = True
# If you're using nspawn, then by default networking will be turned off
# for rpmbuild.  This helps ensure more reproducible builds.
# config_opts['rpmbuild_networking'] = False
```

**Comment by xsuchy** [comment] 2017-08-07 11:14
The mentioned config in in /etc/mock/site-defaults.cfg 
OK. not a bug.
Closing

**Closed by xsuchy** 2017-08-07 11:14 UTC

**Comment by NTMan** [comment] 2019-09-01 00:01
In my case adding `config_opts['rpmbuild_networking'] = True` only solved problem with macro `%define numeric_ver %(curl -s https://raw.githubusercontent.com/daniel-schuermann/mesa/master/VERSION | grep -oP '[0-9.]+')`
Macro `%define build_shortcommit %(git ls-remote %{build_repo} | grep -w "refs/heads/%{build_branch}" | cut -c1-8)` still not working.

In build log, I see error message `sh: git: command not found`, but git command successfuly working under my user in terminal:
```
$ git ls-remote https://github.com/daniel-schuermann/mesa | grep -w "refs/heads/master" | cut -c1-8
f2bed9b3
```
Adding additional options `config_opts['use_nspawn'] = False` and  `config_opts['use_bootstrap_container'] = False` nothing changed.

OS: Fedora Rawhide

**Comment by Frodox** [comment] 2019-09-17 06:58
@NTMan did you install git package inside chroot/mock?

**Comment by NTMan** [comment] 2019-09-17 13:50
> @NTMan did you install git package inside chroot/mock?

How do it? The command `mock install git` seems not to do installation git for all mock builds.

**Comment by praiskup** [comment] 2019-09-17 18:04
BuildRequires?

**Comment by NTMan** [comment] 2019-09-18 06:47
> BuildRequires?

Unfortunately, it not helps. Because the macro should be executed before BuildRequires section.
Example of spec file: https://copr-be.cloud.fedoraproject.org/results/xxmitsu/mesa-aco/fedora-rawhide-x86_64/01034712-mesa/mesa.spec

**Comment by praiskup** [comment] 2019-09-18 07:32
Would this help? 
```diff
diff --git a/mesa.spec b/mesa.spec
index c8d705b..65d33de 100644
--- a/mesa.spec
+++ b/mesa.spec
@@ -20,7 +20,7 @@
 %define source_url %{build_repo}/-/archive/%{build_branch}/mesa-%{build_branch}.zip
 %endif
 
-%define build_shortcommit %(git ls-remote %{build_repo} | grep -w "refs/heads/%{build_branch}" | cut -c1-8)
+%define build_shortcommit %((git ls-remote %{build_repo} || echo 666) | grep -w "refs/heads/%{build_branch}" | cut -c1-8)
 %global build_timestamp %(date +"%Y%m%d")
 %global rel_build %{build_timestamp}.%{build_shortcommit}%{?dist}
 
@@ -111,6 +111,7 @@ BuildRequires:  meson >= 0.45
 BuildRequires:  gcc
 BuildRequires:  gcc-c++
 BuildRequires:  gettext
+BuildRequires:  git
 
 %if 0%{?with_hardware}
 BuildRequires:  kernel-headers
```

**Comment by praiskup** [comment] 2019-09-18 07:34
FWIW, if you are building in copr -- you can put `git` package into minimal buildroot (Project -> Settings -> "Edit" button near the chroot check box -> "Packages" field).

**Comment by NTMan** [comment] 2019-09-18 13:49
> Would this help?

https://paste.fedoraproject.org/paste/kfAE81GVPq-YPc-GEzD2ig
Unfortunately not. Line 34 said that `sh: git: command not found`.

**Comment by praiskup** [comment] 2019-09-18 14:41
That is not an error, just warning, the happens right after that:
`error: line 90: Illegal sequence ".." in: Release:        20190918..fc32`
Well, at the time of creating RPM from SRPM, you are not going to be in git repository anyways - so this can not work.
You need to bake the git version into the spec file in text form, e.g. by some of the copr SCM methods.

**Comment by NTMan** [comment] 2019-09-19 03:54
> That is not an error, just warning, the happens right after that:
> `error: line 90: Illegal sequence ".." in: Release: 20190918..fc32`

These are the consequences of not executing the macro. If the macro `https://github.com/daniel-schuermann/mesa/` would executed inside the mock environment, then everything will work.

Why not allow passthrough some commands in the mock environment (make it configurable)? Or making install some packages permanently by a user?

P.S.
The example I gave is not my CORP.
I build packages locally on my machine.

**Comment by praiskup** [comment] 2019-09-19 04:48
On Thursday, September 19, 2019 5:54:37 AM CEST Mikhail wrote:
> > That is not an error, just warning, the happens right after that:
> > `error: line 90: Illegal sequence ".." in: Release: 20190918..fc32`
> 
> These are the consequences of not executing the macro. If the macro
> `https://github.com/daniel-schuermann/mesa/` would executed inside the mock
> environment, then everything will work.

I misinterpreted the `ls-remote` command.  I thought it is working in cloned
repo.  But

- name/release/version/epoch is not something which should be prone to
  race
  conditions, if you build the same src.rpm in the same chroot, the build
  should (my opinion) produce always the same NVR
- executing the %() script with remote commands anytime when RPM is
  parsing spec file isn't good thing
- people re-building your src.rpm won't know they need to hack mock to put
  'git' into minimal buildroot
- did you count how many times the macro is evaluated, thus executed?

This doesn't smell like a good idea, but I suppose you are working with CI
only packages - so.... with all the said above:

- make sure that the %() macro always returns something, e.g.:
  `git ls-remote https://github.com/daniel-schuermann/mesa | grep -w "refs/heads/master" || echo 666666666666) | cut -c1-8`
  (if git isn't installed, the short commit would be 66666..)
- put git into BuildRequires
- now, when the RPM (not SRPM!) is going to be generated in mock, you
  should have the short commit in Release

> Why not allow passthrough some commands in the mock environment (make it
> configurable)?

Configurable on what level?  Distro/Mock/RPM/spec/..?

> Or making install some packages permanently by a user?

Take a look at `config_opts['chroot_additional_packages'] = ''`.

> P.S.  The example I gave is not my CORP.  I build packages locally on my
> machine. 

Copr only uses `chroot_additional_packages` option, check `copr-cli
mock-config` output.
