### ISSUE TITLE
--no-clean doesn't work with use_nspawn

### ISSUE THREAD

**Issue by kparal** [rpm-software-management/mock#116] opened 2017-09-07 14:51 UTC
If I run `mock --no-clean foo.src.rpm` repeatedly, the BuildRequires packages are installed every time. It seems that `--no-clean` has no effect.

However, if I set `config_opts['use_nspawn'] = False` in `/etc/mock/site-defaults.cfg`, then `--no-clean` starts working fine (BuildRequires are not reinstalled every time).

Seem like either a bug or something that should be mentioned in the man page at `--no-clean` option description.

As one more nitpick, you have:
```
# By default Mock use simple chroot(1). When you set this to True
# it will use systemd-nspawn(1)
# config_opts['use_nspawn'] = True
```
in `/etc/mock/site-defaults.cfg` and it seems to be outdated (simple chroot is not used by default anymore).

mock-1.4.4-1.fc26.noarch

**Comment by kparal** [comment] 2017-10-31 09:13
With `mock-1.4.6-1.fc27.noarch` I can no longer reproduce this. Everything works fine.

**Comment by xsuchy** [comment] 2017-10-31 10:41
I cannot reproduce it either. Closing.

**Closed by xsuchy** 2017-10-31 10:41 UTC
Labels: bug
