### ISSUE TITLE
OSError: [Errno 16] Device or resource busy

### ISSUE THREAD

**Issue by junaruga** [rpm-software-management/mock#145] opened 2017-12-22 15:30 UTC
Hi,
CC: @praiskup

When I ran internal copr, I got below error on the server.
The running mock version in the copr server is 1.4.7.

```
Traceback (most recent call last):
  File "/usr/libexec/mock/mock", line 934, in <module>
    main()
  File "/usr/lib/python3.6/site-packages/mockbuild/trace_decorator.py",
line 96, in trace
    result = func(*args, **kw)
  File "/usr/libexec/mock/mock", line 737, in main
    run_command(options, args, config_opts, commands, buildroot, state)
  File "/usr/lib/python3.6/site-packages/mockbuild/trace_decorator.py",
line 96, in trace
    result = func(*args, **kw)
  File "/usr/libexec/mock/mock", line 821, in run_command
    do_rebuild(config_opts, commands, buildroot, args)
  File "/usr/lib/python3.6/site-packages/mockbuild/trace_decorator.py",
line 96, in trace
    result = func(*args, **kw)
  File "/usr/libexec/mock/mock", line 527, in do_rebuild
    post=post_build, clean=clean)
  File "/usr/lib/python3.6/site-packages/mockbuild/trace_decorator.py",
line 96, in trace
    result = func(*args, **kw)
  File "/usr/libexec/mock/mock", line 492, in rebuild_generic
    commands.clean()
  File "/usr/lib/python3.6/site-packages/mockbuild/trace_decorator.py",
line 96, in trace
    result = func(*args, **kw)
  File "/usr/lib/python3.6/site-packages/mockbuild/backend.py", line
78, in clean
    self.buildroot.delete()
  File "/usr/lib/python3.6/site-packages/mockbuild/trace_decorator.py",
line 96, in trace
    result = func(*args, **kw)
  File "/usr/lib/python3.6/site-packages/mockbuild/buildroot.py", line
607, in delete
    util.rmtree(self.basedir, selinux=self.selinux)
  File "/usr/lib/python3.6/site-packages/mockbuild/trace_decorator.py",
line 96, in trace
    result = func(*args, **kw)
  File "/usr/lib/python3.6/site-packages/mockbuild/util.py", line 151, in rmtree
    rmtree(fullname, selinux=selinux, exclude=exclude)
  File "/usr/lib/python3.6/site-packages/mockbuild/trace_decorator.py",
line 96, in trace
    result = func(*args, **kw)
  File "/usr/lib/python3.6/site-packages/mockbuild/util.py", line 160, in rmtree
    os.rmdir(path)
OSError: [Errno 16] Device or resource busy:
```

The build.log was outputted as a exit status: 0 when I faced the error.

```
+ exit 0
Child return code was: 0
```

There is a same kind of issue reported here.
https://bugzilla.redhat.com/show_bug.cgi?id=1294977

When I ran mock latest version 1.4.7-1 on local, that was not happened.
I guess that this project have already fixed the issue, is it right?

by this commit?
https://github.com/rpm-software-management/mock/commit/54c242348e6c7df142f530aa77c2180e7193c23b

**Comment by xsuchy** [comment] 2019-05-17 13:44
Closing as I do not have reproducer for a long time. Please reopen if you can provide a reproducer.

**Comment by brianjmurrell** [comment] 2023-09-18 17:40
I am currently experiencing this, reproducibly (that is, every run of my build hits this):

```
Traceback (most recent call last):
  File "/usr/libexec/mock/mock", line 1071, in <module>
    exitStatus = main()
                 ^^^^^^
  File "/usr/lib/python3.11/site-packages/mockbuild/trace_decorator.py", line 93, in trace
    result = func(*args, **kw)
             ^^^^^^^^^^^^^^^^^
  File "/usr/libexec/mock/mock", line 831, in main
    result = run_command(options, args, config_opts, commands, buildroot, state)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/mockbuild/trace_decorator.py", line 93, in trace
    result = func(*args, **kw)
             ^^^^^^^^^^^^^^^^^
  File "/usr/libexec/mock/mock", line 945, in run_command
    mockbuild.rebuild.do_rebuild(config_opts, commands, buildroot, options, srpms)
  File "/usr/lib/python3.11/site-packages/mockbuild/trace_decorator.py", line 93, in trace
    result = func(*args, **kw)
             ^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/mockbuild/rebuild.py", line 85, in do_rebuild
    rebuild_generic(srpms, commands, buildroot, config_opts, cmd=build,
  File "/usr/lib/python3.11/site-packages/mockbuild/trace_decorator.py", line 93, in trace
    result = func(*args, **kw)
             ^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/mockbuild/rebuild.py", line 23, in rebuild_generic
    commands.clean()
  File "/usr/lib/python3.11/site-packages/mockbuild/trace_decorator.py", line 93, in trace
    result = func(*args, **kw)
             ^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/mockbuild/backend.py", line 93, in clean
    self.buildroot.delete()
  File "/usr/lib/python3.11/site-packages/mockbuild/trace_decorator.py", line 93, in trace
    result = func(*args, **kw)
             ^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/mockbuild/buildroot.py", line 996, in delete
    file_util.rmtree(self.basedir, selinux=self.selinux)
  File "/usr/lib/python3.11/site-packages/mockbuild/trace_decorator.py", line 93, in trace
    result = func(*args, **kw)
             ^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/mockbuild/file_util.py", line 59, in rmtree
    rmtree(fullname, selinux=selinux, exclude=exclude)
  File "/usr/lib/python3.11/site-packages/mockbuild/trace_decorator.py", line 93, in trace
    result = func(*args, **kw)
             ^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/mockbuild/file_util.py", line 68, in rmtree
    os.rmdir(path)
OSError: [Errno 16] Device or resource busy: '/var/lib/mock/rocky+epel-8-x86_64/result'
```

I am happy to do some debugging of the process/environment if there is anything you can suggest that would be useful to resolving this.

**Comment by brianjmurrell** [comment] 2023-09-19 14:17
In my case this is happening because I run mock in a [Docker] container into which I map a local directory to `/var/lib/mock/rocky+epel-8-x86_64/result` so that the results are written to the host and not lost in the container.  In order to do this I have to run `mock` with `--no-clean` which seems to have gotten dropped from my `mock` command line arguments at some point in the near past.

As an aside, I wonder what possible negative fall-out I might be subject to by always run mock with `--no-clean`.  I suspect I am going to be losing the guarantee of clean build environment and might end up silently missing `BuildRequires:` in my specfiles due to needed BRs being already installed from a previous `mock` run in that container.  Am I correct about that?

**Comment by Conan-Kudo** [comment] 2023-09-19 14:55
> Update: I think it's safe. The fact that I am spawning a new fresh [Docker] container for every build means that there isn't really anything that needs cleaning and `--no-clean` therefore ends up being benign. Am I correct about that?

You are.

**Comment by brianjmurrell** [comment] 2023-09-19 15:00
> You are.

Thank- you for the confirmation.

I would suppose we can close this out again since the cause is understood and it's a side effect of mapping `/var/lib/mock/rocky+epel-8-x86_64/result` into the container.  Unsurprisingly it cannot be deleted and one needs to use `--no-clean` in such situations.

**Comment by praiskup** [comment] 2023-09-20 08:50
Thank you for providing the reasoning.  Closing.

**Closed by praiskup** 2023-09-20 08:50 UTC
Labels: cannot-reproduce
