### ISSUE TITLE
Always use "--disablerepo=sclo*' rather than "--disablerepo sclo* '

### ISSUE THREAD

**Issue by nkadel** [rpm-software-management/mock#387] opened 2019-10-26 17:04 UTC
### Short description of the problem
"--disablerepo *" syntax can be confused by local filenames. Always script with "--disablerepo=" so that local operations, probing yum and dnf operations locally, can be safely copied from configs.

### Output of `rpm -q mock`
mock=1.4.20-1.el8
mock-core-configs-31.6-1

### Steps to reproduce issue

1.
2.
3.

Do not forget to mention full commandline with the mock command you executed.

### Any additional notes

What is there is not broken, it's merely confussing. Files that contain this syntax include:

 * epel-6-x86_64.cg
 * epel-7-x86_64.cg
 * epel-7-aarch64.cg
 * epel-7-ppc641e.cg

**Comment by xsuchy** [comment] 2019-11-01 12:25
Duplicate of https://github.com/rpm-software-management/mock/issues/323

**Closed by xsuchy** 2019-11-01 12:25 UTC
