### ISSUE TITLE
mock --bootstrap-chroot --install foo erroneously bind-mounts foo if it exists in cwd

### ISSUE THREAD

**Issue by ernestask** [rpm-software-management/mock#473] opened 2020-02-11 13:12 UTC
Context: https://github.com/abrt/libreport/commit/74d44b84508a4e107845a26266917c99bd6b8c3b

We have a monstrosity like this (truncated for relevance):
```bash
REQUIRED_PACKAGES=…

…

alias cmock="/usr/bin/mock --bootstrap-chroot --old-chroot -v -r  ${DISTRO}-${ARCH} --configdir=/etc/mock/${TARGET}/"

test -d /var/lib/mock/${DISTRO}-${ARCH}/ || cmock --init

# install required tools for build first
eval cmock --install $REQUIRED_PACKAGES

if grep -q sysdeps autogen.sh ; then
    AU_CHROOT_PATH="/tmp/${TARGET}_sysdeps"
    eval cmock --install $(cmock -q --shell "cd $AU_CHROOT_PATH/; ./autogen.sh sysdeps")
else
    BUILD_REQUIRE=$( grep -oP '^BuildRequires:\s+[^\s]+' *.spec.in | cut -d: -f2 | grep -v '\%')
    cmock --install $BUILD_REQUIRE
fi
```

Some spec files we use this one contain build dependencies on augeas and some projects happen to have an augeas directory with some lenses inside, which makes everything go down in flames when Mock simply bind-mounts the directory and tries to install it.

**Comment by ernestask** [comment] 2020-02-11 13:14
I’ll link to https://github.com/rpm-software-management/mock/commit/151e774b4bceadb0ac3f7f10b1f46bb0f0ece487 here as well for posterity.

**Comment by ernestask** [comment] 2020-02-11 13:18
Another problem is probably that the script passes `--bootstrap-chroot` needlessly *everywhere*.

**Comment by xsuchy** [comment] 2020-02-11 21:25
This is a dupe of #474 which already has associated PR.

**Closed by xsuchy** 2020-02-11 21:25 UTC
