### ISSUE TITLE
running livemedia-creator in mock breaks internet in %post

### ISSUE THREAD

**Issue by axk4545** [rpm-software-management/mock#67] opened 2017-04-20 16:11 UTC
I am the lead for  a Fedora Remix called [TigerOS](https://github.com/RITlug/TigerOS) Recently I discovered that the command on line 365 of the attached ks fails when I use the attached build script. Additionally the `dnf install` on line 374 fails. Is this just a limitation of mock and the nature of chroots?

[ci-build-mock.sh.txt](https://github.com/rpm-software-management/mock/files/944392/ci-build-mock.sh.txt)

[tigeros.ks.txt](https://github.com/rpm-software-management/mock/files/944395/tigeros.ks.txt)

**Comment by xsuchy** [comment] 2017-04-21 10:35
It works for me with mock-1.3.4

**Comment by xsuchy** [comment] 2017-04-24 15:07
Unless there is better reproducer, I am going to close this one.

**Closed by xsuchy** 2017-04-24 15:07 UTC
