### ISSUE TITLE
build with opensuse-leap-15.4-x86_64 config hangs/spins

### ISSUE THREAD

**Issue by brianjmurrell** [rpm-software-management/mock#960] opened 2022-08-24 02:36 UTC
### Output of `rpm -q mock`

```
mock-3.1-1.fc36.noarch
```

### Steps to reproduce issue

1. rpmbuild -bs foo.spec
2. mock -r opensuse-leap-15.4-x86_64
[mock-out.txt](https://github.com/rpm-software-management/mock/files/9411925/mock-out.txt)

### Any additional notes

<details>
  <summary>
    <p>Output of `mock --debug-config`</p>
  </summary>

```
INFO: mock.py version 3.1 starting (python version = 3.10.6, NVR = mock-3.1-1.fc36)...
Start(bootstrap): init plugins
INFO: selinux enabled
Finish(bootstrap): init plugins
Start: init plugins
INFO: selinux enabled
Finish: init plugins
INFO: Signal handler active
Start: run
config_opts['additional_packages'] = []
config_opts['bootstrap_image'] = 'registry.opensuse.org/opensuse/leap-dnf:15.4'
config_opts['build_log_fmt_str'] = '%(message)s'
config_opts['cache_alterations'] = False
config_opts['chroot_name'] = 'opensuse-leap-15.4-x86_64'
config_opts['chroot_setup_cmd'] = 'install patterns-devel-base-devel_rpm_build'
config_opts['cleanup_on_failure'] = False
config_opts['cleanup_on_success'] = False
config_opts['config_file'] = '/etc/mock/opensuse-leap-15.4-x86_64.cfg'
config_opts['config_path'] = '/etc/mock'
config_opts['config_paths'] = ['/etc/mock/site-defaults.cfg',
 '/etc/mock/chroot-aliases.cfg',
 '/etc/mock/opensuse-leap-15.4-x86_64.cfg',
 '/etc/mock/templates/opensuse-leap-15.4.tpl']
config_opts['description'] = 'openSUSE Leap {{ releasever }}'
config_opts['dist'] = 'suse.lp154'
config_opts['dnf.conf'] = ('\n'
 '[main]\n'
 'keepcache=1\n'
 'debuglevel=2\n'
 'reposdir=/dev/null\n'
 'logfile=/var/log/yum.log\n'
 'retries=20\n'
 'obsoletes=1\n'
 'gpgcheck=0\n'
 'assumeyes=1\n'
 'syslog_ident=mock\n'
 'syslog_device=\n'
 'install_weak_deps=0\n'
 'metadata_expire=0\n'
 'best=1\n'
 "{% if target_arch == 'x86_64' %}\n"
 'excludepkgs=*.i586,*.i686,*.ppc,*.ppc64,*.ppc64le,*.s390x\n'
 "{% elif target_arch == 'i586' %}\n"
 'excludepkgs=*.x86_64,*.ppc,*.ppc64,*.ppc64le,*.s390x\n'
 "{% elif target_arch == 'ppc64le' %}\n"
 'excludepkgs=*.ppc,*.ppc64,*.x86_64,*.i586,*.i686,*.s390x\n'
 "{% elif target_arch == 'ppc64' %}\n"
 'excludepkgs=*.ppc,*.ppc64le,*.x86_64,*.i586,*.i686,*.s390x\n'
 "{% elif target_arch == 's390x' %}\n"
 'excludepkgs=*.ppc,*.ppc64,*.ppc64le,*.x86_64,*.i586,*.i686\n'
 '{% endif %}\n'
 '\n'
 'protected_packages=\n'
 'user_agent={{ user_agent }}\n'
 '\n'
 '# repos\n'
 '\n'
 '[opensuse-leap-oss]\n'
 'name=openSUSE Leap $releasever - {{ target_arch }} - OSS\n'
 'baseurl=https://download.opensuse.org/distribution/leap/$releasever/repo/oss/\n'
 '#metalink=https://download.opensuse.org/distribution/leap/$releasever/repo/oss/repodata/repomd.xml.metalink\n'
 'enabled=1\n'
 'gpgkey=file:///usr/share/distribution-gpg-keys/opensuse/RPM-GPG-KEY-openSUSE\n'
 '        '
 'file:///usr/share/distribution-gpg-keys/opensuse/RPM-GPG-KEY-openSUSE-Backports\n'
 '        '
 'file:///usr/share/distribution-gpg-keys/suse/RPM-GPG-KEY-SuSE-SLE-15\n'
 'gpgcheck=1\n'
 '\n'
 '[opensuse-leap-oss-update]\n'
 'name=openSUSE Leap $releasever - {{ target_arch }} - OSS - Updates\n'
 'baseurl=https://download.opensuse.org/update/leap/$releasever/oss/\n'
 '#metalink=https://download.opensuse.org/update/leap/$releasever/oss/repodata/repomd.xml.metalink\n'
 'enabled=1\n'
 'gpgkey=file:///usr/share/distribution-gpg-keys/opensuse/RPM-GPG-KEY-openSUSE\n'
 'gpgcheck=1\n'
 '\n'
 '[opensuse-leap-sle-update]\n'
 'name=openSUSE Leap $releasever - {{ target_arch }} - Updates from SUSE Linux '
 'Enterprise\n'
 'baseurl=https://download.opensuse.org/update/leap/$releasever/sle/\n'
 '#metalink=https://download.opensuse.org/update/leap/$releasever/sle/repodata/repomd.xml.metalink\n'
 'enabled=1\n'
 'gpgkey=file:///usr/share/distribution-gpg-keys/suse/RPM-GPG-KEY-SuSE-SLE-15\n'
 'gpgcheck=1\n'
 '\n'
 '[opensuse-leap-sle-backports-update]\n'
 'name=openSUSE Leap $releasever - {{ target_arch }} - Updates from Backports '
 'for SUSE Linux Enterprise\n'
 'baseurl=https://download.opensuse.org/update/leap/$releasever/backports/\n'
 '#metalink=https://download.opensuse.org/update/leap/$releasever/backports/repodata/repomd.xml.metalink\n'
 'enabled=1\n'
 'gpgkey=file:///usr/share/distribution-gpg-keys/opensuse/RPM-GPG-KEY-openSUSE-Backports\n'
 'gpgcheck=1\n'
 '\n')
config_opts['enable_disable_repos'] = []
config_opts['extra_chroot_dirs'] = ['/run/lock']
config_opts['files'] = {'etc/hosts': '127.0.0.1 localhost localhost.localdomain\n'
              '::1       localhost localhost.localdomain localhost6 '
              'localhost6.localdomain6\n'}
config_opts['legal_host_arches'] = ('x86_64',)
config_opts['macros'] = {'%_buildhost': 'builder.example.com',
 '%_platform_multiplier': 1,
 '%_rpmfilename': '%%{NAME}-%%{VERSION}-%%{RELEASE}.%%{ARCH}.rpm',
 '%_topdir': '/builddir/build',
 '%dist': '.suse.lp154'}
config_opts['no-config'] = {'epel-8': {'alternatives': {'alma+epel-8': {'description': ['Builds against '
                                                             'AlmaLinux 8 '
                                                             'repositories, '
                                                             'together with '
                                                             'the official '
                                                             'EPEL '
                                                             'repositories.',
                                                             'Project page: '
                                                             'https://almalinux.org/']},
                             'centos-stream+epel-8': {'description': ['Builds '
                                                                      'against '
                                                                      'CentOS '
                                                                      'Stream '
                                                                      '8 '
                                                                      'repositories '
                                                                      '(some '
                                                                      'packages '
                                                                      'may be '
                                                                      'a bit '
                                                                      'ahead '
                                                                      'the Red '
                                                                      'Hat '
                                                                      'Enterprise '
                                                                      'Linux '
                                                                      '8) '
                                                                      'together '
                                                                      'with '
                                                                      'the '
                                                                      'official '
                                                                      'EPEL 8 '
                                                                      'repositories.',
                                                                      'Project '
                                                                      'page: '
                                                                      'https://www.centos.org/centos-stream/']},
                             'circlelinux+epel-8': {'description': ['Builds '
                                                                    'against '
                                                                    'Circle '
                                                                    'Linux 8 '
                                                                    'repositories, '
                                                                    'together '
                                                                    'with the '
                                                                    'official '
                                                                    'EPEL '
                                                                    'repositories.',
                                                                    'Project '
                                                                    'page: '
                                                                    'https://cclinux.org/']},
                             'rhel+epel-8': {'description': ['Builds against '
                                                             'Red Hat '
                                                             'Enterprise Linux '
                                                             '8 repositories, '
                                                             'together with '
                                                             'the official '
                                                             'EPEL '
                                                             'repositories.',
                                                             'This mimics what '
                                                             'is done in the '
                                                             'official EPEL '
                                                             'build system, '
                                                             'but you need a '
                                                             'Red Hat '
                                                             'subscription:',
                                                             'https://rpm-software-management.github.io/mock/Feature-rhelchroots']},
                             'rocky+epel-8': {'description': ['Builds against '
                                                              'Rocky Linux 8 '
                                                              'repositories, '
                                                              'together with '
                                                              'the official '
                                                              'EPEL '
                                                              'repositories.',
                                                              'Project page: '
                                                              'https://rockylinux.org/']}}},
 'epel-9': {'alternatives': {'alma+epel-9': {'description': ['Builds against '
                                                             'AlmaLinux 9 '
                                                             'repositories, '
                                                             'together with '
                                                             'the official '
                                                             'EPEL '
                                                             'repositories.',
                                                             'Project page: '
                                                             'https://almalinux.org/']},
                             'centos-stream+epel-9': {'description': ['Builds '
                                                                      'against '
                                                                      'CentOS '
                                                                      'Stream '
                                                                      '9 '
                                                                      'repositories '
                                                                      '(some '
                                                                      'packages '
                                                                      'may be '
                                                                      'a bit '
                                                                      'ahead '
                                                                      'the Red '
                                                                      'Hat '
                                                                      'Enterprise '
                                                                      'Linux '
                                                                      '9) '
                                                                      'together '
                                                                      'with '
                                                                      'the '
                                                                      'official '
                                                                      'EPEL '
                                                                      'repositories.',
                                                                      'Project '
                                                                      'page: '
                                                                      'https://www.centos.org/centos-stream/']},
                             'rhel+epel-9': {'description': ['Builds against '
                                                             'Red Hat '
                                                             'Enterprise Linux '
                                                             '9 repositories, '
                                                             'together with '
                                                             'the official '
                                                             'EPEL '
                                                             'repositories.',
                                                             'This mimics what '
                                                             'is done in the '
                                                             'official EPEL '
                                                             'build system, '
                                                             'but you need a '
                                                             'Red Hat '
                                                             'subscription:',
                                                             'https://rpm-software-management.github.io/mock/Feature-rhelchroots']},
                             'rocky+epel-9': {'description': ['Builds against '
                                                              'Rocky Linux 9 '
                                                              'repositories, '
                                                              'together with '
                                                              'the official '
                                                              'EPEL '
                                                              'repositories.',
                                                              'Project page: '
                                                              'https://rockylinux.org/']}}}}
config_opts['nspawn_args'] = ['--capability=cap_ipc_lock',
 '--bind=/tmp/mock-resolv.ji9pgzb9:/etc/resolv.conf',
 '--bind=/dev/btrfs-control',
 '--bind=/dev/loop-control',
 '--bind=/dev/loop0',
 '--bind=/dev/loop1',
 '--bind=/dev/loop2',
 '--bind=/dev/loop3',
 '--bind=/dev/loop4',
 '--bind=/dev/loop5',
 '--bind=/dev/loop6',
 '--bind=/dev/loop7',
 '--bind=/dev/loop8',
 '--bind=/dev/loop9',
 '--bind=/dev/loop10',
 '--bind=/dev/loop11']
config_opts['package_manager_attempt_delay'] = 20
config_opts['package_manager_max_attempts'] = 4
config_opts['plugin_conf'] = {'bind_mount_enable': True,
 'bind_mount_opts': {'basedir': '/var/lib/mock/opensuse-leap-15.4-x86_64',
                     'cache_topdir': '/var/cache/mock',
                     'cachedir': '/var/cache/mock/opensuse-leap-15.4-x86_64',
                     'create_dirs': False,
                     'dirs': [],
                     'resultdir': '/var/lib/mock/opensuse-leap-15.4-x86_64/result',
                     'root': 'opensuse-leap-15.4-x86_64'},
 'ccache_enable': False,
 'ccache_opts': {'basedir': '/var/lib/mock/opensuse-leap-15.4-x86_64',
                 'cache_topdir': '/var/cache/mock',
                 'cachedir': '/var/cache/mock/opensuse-leap-15.4-x86_64',
                 'compress': None,
                 'dir': '/var/cache/mock/opensuse-leap-15.4-x86_64/ccache/u1001/',
                 'max_cache_size': '4G',
                 'resultdir': '/var/lib/mock/opensuse-leap-15.4-x86_64/result',
                 'root': 'opensuse-leap-15.4-x86_64'},
 'chroot_scan_enable': False,
 'chroot_scan_opts': {'basedir': '/var/lib/mock/opensuse-leap-15.4-x86_64',
                      'cache_topdir': '/var/cache/mock',
                      'cachedir': '/var/cache/mock/opensuse-leap-15.4-x86_64',
                      'only_failed': True,
                      'regexes': ['^[^k]?core(\\.\\d+)?$', '\\.log$'],
                      'resultdir': '/var/lib/mock/opensuse-leap-15.4-x86_64/result',
                      'root': 'opensuse-leap-15.4-x86_64'},
 'compress_logs_enable': False,
 'compress_logs_opts': {'basedir': '/var/lib/mock/opensuse-leap-15.4-x86_64',
                        'cache_topdir': '/var/cache/mock',
                        'cachedir': '/var/cache/mock/opensuse-leap-15.4-x86_64',
                        'command': 'gzip',
                        'resultdir': '/var/lib/mock/opensuse-leap-15.4-x86_64/result',
                        'root': 'opensuse-leap-15.4-x86_64'},
 'hw_info_enable': True,
 'hw_info_opts': {'basedir': '/var/lib/mock/opensuse-leap-15.4-x86_64',
                  'cache_topdir': '/var/cache/mock',
                  'cachedir': '/var/cache/mock/opensuse-leap-15.4-x86_64',
                  'resultdir': '/var/lib/mock/opensuse-leap-15.4-x86_64/result',
                  'root': 'opensuse-leap-15.4-x86_64'},
 'lvm_root_enable': False,
 'lvm_root_opts': {'basedir': '/var/lib/mock/opensuse-leap-15.4-x86_64',
                   'cache_topdir': '/var/cache/mock',
                   'cachedir': '/var/cache/mock/opensuse-leap-15.4-x86_64',
                   'pool_name': 'mockbuild',
                   'resultdir': '/var/lib/mock/opensuse-leap-15.4-x86_64/result',
                   'root': 'opensuse-leap-15.4-x86_64'},
 'mount_enable': True,
 'mount_opts': {'basedir': '/var/lib/mock/opensuse-leap-15.4-x86_64',
                'cache_topdir': '/var/cache/mock',
                'cachedir': '/var/cache/mock/opensuse-leap-15.4-x86_64',
                'dirs': [],
                'resultdir': '/var/lib/mock/opensuse-leap-15.4-x86_64/result',
                'root': 'opensuse-leap-15.4-x86_64'},
 'overlayfs_enable': False,
 'overlayfs_opts': {'basedir': '/var/lib/mock/opensuse-leap-15.4-x86_64',
                    'cache_topdir': '/var/cache/mock',
                    'cachedir': '/var/cache/mock/opensuse-leap-15.4-x86_64',
                    'resultdir': '/var/lib/mock/opensuse-leap-15.4-x86_64/result',
                    'root': 'opensuse-leap-15.4-x86_64'},
 'package_state_enable': True,
 'package_state_opts': {'available_pkgs': False,
                        'basedir': '/var/lib/mock/opensuse-leap-15.4-x86_64',
                        'cache_topdir': '/var/cache/mock',
                        'cachedir': '/var/cache/mock/opensuse-leap-15.4-x86_64',
                        'installed_pkgs': True,
                        'resultdir': '/var/lib/mock/opensuse-leap-15.4-x86_64/result',
                        'root': 'opensuse-leap-15.4-x86_64'},
 'pm_request_enable': False,
 'pm_request_opts': {'basedir': '/var/lib/mock/opensuse-leap-15.4-x86_64',
                     'cache_topdir': '/var/cache/mock',
                     'cachedir': '/var/cache/mock/opensuse-leap-15.4-x86_64',
                     'resultdir': '/var/lib/mock/opensuse-leap-15.4-x86_64/result',
                     'root': 'opensuse-leap-15.4-x86_64'},
 'procenv_enable': False,
 'procenv_opts': {'basedir': '/var/lib/mock/opensuse-leap-15.4-x86_64',
                  'cache_topdir': '/var/cache/mock',
                  'cachedir': '/var/cache/mock/opensuse-leap-15.4-x86_64',
                  'resultdir': '/var/lib/mock/opensuse-leap-15.4-x86_64/result',
                  'root': 'opensuse-leap-15.4-x86_64'},
 'root_cache_enable': True,
 'root_cache_opts': {'age_check': True,
                     'basedir': '/var/lib/mock/opensuse-leap-15.4-x86_64',
                     'cache_topdir': '/var/cache/mock',
                     'cachedir': '/var/cache/mock/opensuse-leap-15.4-x86_64',
                     'compress_program': 'pigz',
                     'decompress_program': None,
                     'dir': '/var/cache/mock/opensuse-leap-15.4-x86_64/root_cache/',
                     'exclude_dirs': ['./proc',
                                      './sys',
                                      './dev',
                                      './tmp/ccache',
                                      './var/cache/yum',
                                      './var/cache/dnf',
                                      './var/log'],
                     'extension': '.gz',
                     'max_age_days': 15,
                     'resultdir': '/var/lib/mock/opensuse-leap-15.4-x86_64/result',
                     'root': 'opensuse-leap-15.4-x86_64'},
 'rpkg_preprocessor_enable': False,
 'rpkg_preprocessor_opts': {'basedir': '/var/lib/mock/opensuse-leap-15.4-x86_64',
                            'cache_topdir': '/var/cache/mock',
                            'cachedir': '/var/cache/mock/opensuse-leap-15.4-x86_64',
                            'cmd': '/usr/bin/preproc-rpmspec %(source_spec)s '
                                   '--output %(target_spec)s',
                            'requires': ['preproc-rpmspec'],
                            'resultdir': '/var/lib/mock/opensuse-leap-15.4-x86_64/result',
                            'root': 'opensuse-leap-15.4-x86_64'},
 'selinux_enable': True,
 'selinux_opts': {'basedir': '/var/lib/mock/opensuse-leap-15.4-x86_64',
                  'cache_topdir': '/var/cache/mock',
                  'cachedir': '/var/cache/mock/opensuse-leap-15.4-x86_64',
                  'resultdir': '/var/lib/mock/opensuse-leap-15.4-x86_64/result',
                  'root': 'opensuse-leap-15.4-x86_64'},
 'showrc_enable': False,
 'showrc_opts': {'basedir': '/var/lib/mock/opensuse-leap-15.4-x86_64',
                 'cache_topdir': '/var/cache/mock',
                 'cachedir': '/var/cache/mock/opensuse-leap-15.4-x86_64',
                 'resultdir': '/var/lib/mock/opensuse-leap-15.4-x86_64/result',
                 'root': 'opensuse-leap-15.4-x86_64'},
 'sign_enable': False,
 'sign_opts': {'basedir': '/var/lib/mock/opensuse-leap-15.4-x86_64',
               'cache_topdir': '/var/cache/mock',
               'cachedir': '/var/cache/mock/opensuse-leap-15.4-x86_64',
               'cmd': 'rpmsign',
               'opts': '--addsign %(rpms)s',
               'resultdir': '/var/lib/mock/opensuse-leap-15.4-x86_64/result',
               'root': 'opensuse-leap-15.4-x86_64'},
 'tmpfs_enable': False,
 'tmpfs_opts': {'basedir': '/var/lib/mock/opensuse-leap-15.4-x86_64',
                'cache_topdir': '/var/cache/mock',
                'cachedir': '/var/cache/mock/opensuse-leap-15.4-x86_64',
                'keep_mounted': False,
                'max_fs_size': None,
                'mode': '0755',
                'required_ram_mb': 900,
                'resultdir': '/var/lib/mock/opensuse-leap-15.4-x86_64/result',
                'root': 'opensuse-leap-15.4-x86_64'},
 'yum_cache_enable': True,
 'yum_cache_opts': {'basedir': '/var/lib/mock/opensuse-leap-15.4-x86_64',
                    'cache_topdir': '/var/cache/mock',
                    'cachedir': '/var/cache/mock/opensuse-leap-15.4-x86_64',
                    'max_age_days': 30,
                    'max_metadata_age_days': 30,
                    'online': True,
                    'resultdir': '/var/lib/mock/opensuse-leap-15.4-x86_64/result',
                    'root': 'opensuse-leap-15.4-x86_64'}}
config_opts['print_main_output'] = True
config_opts['releasever'] = '15.4'
config_opts['root'] = 'opensuse-leap-15.4-x86_64'
config_opts['root_log_fmt_str'] = '%(levelname)s %(filename)s:%(lineno)d:  %(message)s'
config_opts['rpmbuild_arch'] = 'x86_64'
config_opts['ssl_ca_bundle_path'] = '/var/lib/ca-certificates/ca-bundle.pem'
config_opts['state_log_fmt_str'] = '%(asctime)s - %(message)s'
config_opts['target_arch'] = 'x86_64'
config_opts['useradd'] = ('/usr/sbin/useradd -o -m -u {{chrootuid}} -g {{chrootgid}} -d {{chroothome}} '
 '{{chrootuser}}')
config_opts['verbose'] = 1
Finish: run
```
</details>

**Comment by garybuhrmaster** [comment] 2022-08-24 04:40
Looks to be (essentially) the same as #915

**Comment by xsuchy** [comment] 2022-08-24 06:44
Yes, it is a duplicate of #915

**Closed by xsuchy** 2022-08-24 06:44 UTC
